export const colorSchemes = {
  'San Francisco': {
    bg: 'bg-red-950',
    heroBg: 'bg-red-800',
    overlay: 'bg-red-900/30',
    cardBg: 'bg-white',
    border: 'border-gray-200',
    innerBg: 'bg-gray-50',
    trustBg: 'bg-gray-50',
    trustBorder: 'border-gray-200',
  },
  'Taipei': {
    bg: 'bg-green-950',
    heroBg: 'bg-green-800',
    overlay: 'bg-green-900/30',
    cardBg: 'bg-white',
    border: 'border-gray-200',
    innerBg: 'bg-gray-50',
    trustBg: 'bg-gray-50',
    trustBorder: 'border-gray-200',
  },
  'Seoul': {
    bg: 'bg-purple-950',
    heroBg: 'bg-purple-800',
    overlay: 'bg-purple-900/30',
    cardBg: 'bg-white',
    border: 'border-gray-200',
    innerBg: 'bg-gray-50',
    trustBg: 'bg-gray-50',
    trustBorder: 'border-gray-200',
  },
  'Buenos Aires': {
    bg: 'bg-white',
    heroBg: 'bg-yellow-800',
    overlay: 'bg-yellow-900/30',
    cardBg: 'bg-white',
    border: 'border-gray-200',
    innerBg: 'bg-gray-50',
    trustBg: 'bg-gray-50',
    trustBorder: 'border-gray-200',
  },
  'Hyderabad': {
    bg: 'bg-orange-950',
    heroBg: 'bg-orange-800',
    overlay: 'bg-orange-900/30',
    cardBg: 'bg-white',
    border: 'border-gray-200',
    innerBg: 'bg-gray-50',
    trustBg: 'bg-gray-50',
    trustBorder: 'border-gray-200',
  },
};

export const defaultScheme = {
  bg: 'bg-slate-950',
  heroBg: 'bg-slate-800',
  overlay: 'bg-slate-900/30',
  cardBg: 'bg-white',
  border: 'border-gray-200',
  innerBg: 'bg-gray-50',
  trustBg: 'bg-gray-50',
  trustBorder: 'border-gray-200',
};